name: CI/CD with Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

    
    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: my-codebuild-job2
          disable-source-override: true
          buildspec-override: |
            version: 0.2
            phases:
              install:
                commands:
                  - git fetch --depth=1
                  - git checkout --force ${{ github.sha }}
                  - git lfs pull
                  - sudo yum install -y yum-utils
                  - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
                  - sudo yum -y install terraform
                  - terraform --version

              pre_build:
                commands:
                  - echo "Pre-build phase"
              build:
                commands:
                  - terraform init 
                  - terraform destroy -auto-approve

              post_build:
                commands:
                  - echo "Post-build phase"